title: 'Drifters with Pencils'
author:
  name: 'Jan Ong'
  email: JETZero3@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Drifters with Pencils is a webcomic. It contains stick figures, terrible puns, and silly scenarios. '
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
